from pydantic import BaseModel
from typing import Optional

class ToDo(BaseModel):
    id: Optional[str] = None  # must set this to Optional with None as default, as when POST, no id will be provided, id is generated by MongoDB
    title: str
    description: str

class ToDoResponse(BaseModel):
    message: str
    to_do: ToDo